sico_webapp/src/main/java/es/csic/sico/web/webapp/action/convocatorias/action/AyudasConvocatoriaAction.java
package es.csic.sico.web.webapp.action.convocatorias.action;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import es.cisc.sico.core.convocatoria.dto.DatosGeneralesConvocatoriaDTO;
import es.csic.sico.core.externalws.ayuda.dto.AyudaConvocatoriaDTO;
import es.csic.sico.web.facade.AyudaBusinessFacade;
import es.csic.sico.web.webapp.action.convocatorias.action.tab.AbstractConvocatoriaAction;

/**
 * RF005_002
 */
@ManagedBean(name = "ayudasConvocatoriaAction")
@ViewScoped
public class AyudasConvocatoriaAction implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 5902853407778237865L;
    private final Logger log = LoggerFactory.getLogger(getClass());

    @ManagedProperty("#{ayudaBusinessFacade}")
    protected AyudaBusinessFacade ayudaBusinessFacade;

    private List<AyudaConvocatoriaDTO> ayudaConvocatoriaDTOList;
    private AyudaConvocatoriaDTO selectedAyudaConvocatoriaDTO;

    @PostConstruct
    public void init() {

        FacesContext facesContext = FacesContext.getCurrentInstance();
        HttpSession session = (HttpSession) facesContext.getExternalContext().getSession(true);
        DatosGeneralesConvocatoriaDTO datosGeneralesConvocatoriaDTO = (DatosGeneralesConvocatoriaDTO) session.getAttribute(AbstractConvocatoriaAction.DATOS_GENERALES_DTO_SESSION_NAME);

        if (datosGeneralesConvocatoriaDTO != null) {
            ayudaConvocatoriaDTOList = ayudaBusinessFacade.getAyudaConvocatoriaByConvocatoriaId(datosGeneralesConvocatoriaDTO.getId());
        } else {
            ayudaConvocatoriaDTOList = new ArrayList<AyudaConvocatoriaDTO>();
            log.warn("There is not set a DatosGeneralesConvocatoriaDTO in session, because of that ayudaConvocatoriaDTOList will be empty");
        }
    }

    public List<String> getSelectedAyudaConvocatoriaAditionalFieldKeySet() {

        if (selectedAyudaConvocatoriaDTO != null) {
            return new ArrayList<String>(selectedAyudaConvocatoriaDTO.getAditionalField().keySet());

        } else {
            return new ArrayList<String>();

        }

    }

    /**************** SETTERS && GETTERS ****************************/

    public List<AyudaConvocatoriaDTO> getAyudaConvocatoriaDTOList() {
        return ayudaConvocatoriaDTOList;
    }

    public void setAyudaConvocatoriaDTOList(List<AyudaConvocatoriaDTO> ayudaConvocatoriaDTOList) {
        this.ayudaConvocatoriaDTOList = ayudaConvocatoriaDTOList;
    }

    public AyudaConvocatoriaDTO getSelectedAyudaConvocatoriaDTO() {
        return selectedAyudaConvocatoriaDTO;
    }

    public void setSelectedAyudaConvocatoriaDTO(AyudaConvocatoriaDTO selectedAyudaConvocatoriaDTO) {
        this.selectedAyudaConvocatoriaDTO = selectedAyudaConvocatoriaDTO;
    }

    public AyudaBusinessFacade getAyudaBusinessFacade() {
        return ayudaBusinessFacade;
    }

    public void setAyudaBusinessFacade(AyudaBusinessFacade ayudaBusinessFacade) {
        this.ayudaBusinessFacade = ayudaBusinessFacade;
    }
}

sico_webapp/src/main/java/es/csic/sico/web/webapp/action/convocatorias/action/ConvocatoriaAction.java
package es.csic.sico.web.webapp.action.convocatorias.action;

import java.io.IOException;
import java.io.Serializable;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.primefaces.component.tabview.TabView;
import org.primefaces.context.RequestContext;
import org.primefaces.event.TabChangeEvent;

import es.cisc.sico.core.convocatoria.dto.DatosGeneralesConvocatoriaDTO;

/**
 * RF001_004
 */
@ManagedBean(name = "convocatoriaAction")
@ViewScoped
public class ConvocatoriaAction implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 3265408083420291470L;

    private int activeIndex;

    private final Log log = LogFactory.getLog(getClass());

    public static final String NUEVA_CONVOCATORIA_PAGE = "nuevaConvocatoria.html";
    public static final String EDICION_CONVOCATORIA_PAGE = "edicionConvocatoria.html";
    public static final String LISTADO_CONVOCATORIA_PAGE = "/pages/convocatorias/consultaConvocatoria/consultaConvocatoria.html";
    private static final String DATOS_GENERALES_DTO = "datosGeneralesConvocatoriaDTO";
    private static final String TAB_VIEW_ID = "tabPanel";
    private static final String BORRADOR = "edicionBorrador";
    private static final String ACCORDION_PANEL_VALIDATOR_FIELDS = "formValidate";

    @PostConstruct
    public void init() {
        activeIndex = 0;
        FacesContext facesContext = FacesContext.getCurrentInstance();
        HttpSession session = (HttpSession) facesContext.getExternalContext().getSession(true);
        DatosGeneralesConvocatoriaDTO datosGeneralesConvocatoriaDTO = (DatosGeneralesConvocatoriaDTO) session.getAttribute(DATOS_GENERALES_DTO);
        HttpServletRequest origRequest = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
        if (origRequest.getRequestURL().indexOf(NUEVA_CONVOCATORIA_PAGE) != -1 && datosGeneralesConvocatoriaDTO != null) {
            session.setAttribute(DATOS_GENERALES_DTO, null);
        }
        if (session.getAttribute(BORRADOR) != null) {
            boolean edicionBorrador = (Boolean) session.getAttribute(BORRADOR);
            if (edicionBorrador) {
                session.setAttribute(DATOS_GENERALES_DTO, datosGeneralesConvocatoriaDTO);
                session.setAttribute(BORRADOR, false);
            }
        } else {
            session.setAttribute(DATOS_GENERALES_DTO, datosGeneralesConvocatoriaDTO);
        }
        if (origRequest.getRequestURL().indexOf(EDICION_CONVOCATORIA_PAGE) != -1 && datosGeneralesConvocatoriaDTO == null) {
            try {
                FacesContext.getCurrentInstance().getExternalContext().redirect(origRequest.getContextPath() + LISTADO_CONVOCATORIA_PAGE);
            } catch (IOException e) {
                log.warn("Error en redireccion: ", e);
            }
        }
    }

    public void tabIsChanged(TabChangeEvent event) {
        FacesContext context = FacesContext.getCurrentInstance();
        Map<String, String> params = context.getExternalContext().getRequestParameterMap();
        TabView tabView = (TabView) event.getComponent();
        String activeIndexValue = params.get(tabView.getClientId(context) + "_tabindex");

        this.activeIndex = Integer.parseInt(activeIndexValue);
    }

    public void nextTab() {
        activeIndex++;
        RequestContext.getCurrentInstance().update(TAB_VIEW_ID);
        RequestContext.getCurrentInstance().update(ACCORDION_PANEL_VALIDATOR_FIELDS);
    }

    public void previousTab() {
        activeIndex--;
        RequestContext.getCurrentInstance().update(TAB_VIEW_ID);
        RequestContext.getCurrentInstance().update(ACCORDION_PANEL_VALIDATOR_FIELDS);
    }

    /********* SETTER & GETTERS ***********************/

    public int getActiveIndex() {
        return activeIndex;
    }

    public void setActiveIndex(int activeIndex) {
        this.activeIndex = activeIndex;
    }
}

sico_webapp/src/main/java/es/csic/sico/web/webapp/action/convocatorias/action/tab/AbstractConvocatoriaAction.java
package es.csic.sico.web.webapp.action.convocatorias.action.tab;

import java.io.IOException;
import java.util.Collection;
import java.util.HashMap;

import javax.faces.application.FacesMessage;
import javax.faces.application.FacesMessage.Severity;
import javax.faces.bean.ManagedProperty;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.primefaces.context.RequestContext;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;

import es.cisc.sico.core.convocatoria.dto.DatosGeneralesConvocatoriaDTO;
import es.csic.sico.web.facade.ConvocatoriaBusinessFacade;
import es.csic.sico.web.webapp.action.convocatorias.action.ConvocatoriaAction;
import es.csic.sico.web.webapp.action.convocatorias.action.NotificacionConvocatoriasAction;
import es.csic.sico.web.webapp.action.convocatorias.constants.ConvocatoriaStatusEnum;

public abstract class AbstractConvocatoriaAction {

    protected DatosGeneralesConvocatoriaDTO datosGeneralesConvocatoriaDTO;

    @ManagedProperty(value = "#{convocatoriaAction}")
    private ConvocatoriaAction convocatoriaAction;

    @ManagedProperty("#{convBusinessFacade}")
    protected ConvocatoriaBusinessFacade convBusinessFacade;

    @ManagedProperty(value = "#{notificacionConvocatoriaAction}")
    private NotificacionConvocatoriasAction notificacionConvocatoriaAction;

    protected static final String GESTOR_CONVOCATORIA_ROL = "SICO-CONV-GES";

    private static final String GESTOR_PARCIAL_CONVOCATORIA_ROL = "SICO-CONV-GESP";

    public static final String DATOS_GENERALES_DTO_SESSION_NAME = "datosGeneralesConvocatoriaDTO";

    private static final String SUCCESS_SAVE_MESSAGE = "Se ha guardado sus cambios exitosamente";

    private static final String FAIL_SAVE_MESSAGE = "No se pudo guardar sus cambios exitosamente";

    protected static final String FAIL_ERROR_INTERNO_MESSAGE = "No se pudo cargar los datos";

    private static final String INFORMATIVE_MESSAGE = "Mensaje Informativo";

    protected static final String FORM_VALIDATE_PROGRESS_JSF_ID = "formValidate:progress";
    protected static final String FORM_VALIDATE_PANEL_VALIDATION_JSF_ID = "formValidate:panelValidacion";
    protected static final String FORM_VALIDATE_ACTION_JSF_ID = "formValidate:action";

    private final Log abstractLogger = LogFactory.getLog(getClass());

    protected HashMap<String,Boolean> fieldsStatus;
    
    protected boolean isEdit;
    
    public boolean isEdition() {
        FacesContext facesContext = FacesContext.getCurrentInstance();
        HttpSession session = (HttpSession) facesContext.getExternalContext().getSession(true);
        DatosGeneralesConvocatoriaDTO datosGeneralesConvocatoriaDTOAux = (DatosGeneralesConvocatoriaDTO) session.getAttribute(DATOS_GENERALES_DTO_SESSION_NAME);
        boolean isEdition = false;

        if (datosGeneralesConvocatoriaDTOAux != null) {
            datosGeneralesConvocatoriaDTO = datosGeneralesConvocatoriaDTOAux;
            isEdition = true;
        }
        isEdit = isEdition;
        return isEdition;
    }

    public boolean isNuevaConvocatoriaPage() {
        HttpServletRequest origRequest = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
        return origRequest.getRequestURL().indexOf(ConvocatoriaAction.NUEVA_CONVOCATORIA_PAGE) != -1;
    }

    protected abstract void initFieldsStatus();
    
    public abstract void save();

    public abstract int getPercentage();

    public abstract void validate();

    public void saveAndSend() throws IOException {
        long previousStatus;
        this.save();
        this.getDatosGeneralesConvocatoriaDTOInSession();
        if (datosGeneralesConvocatoriaDTO.getId() != null) {
            if (datosGeneralesConvocatoriaDTO.getStatusName().equals(ConvocatoriaStatusEnum.POR_SUBSANAR.getName())) {
                previousStatus = datosGeneralesConvocatoriaDTO.getStatus();
                datosGeneralesConvocatoriaDTO.setStatus(ConvocatoriaStatusEnum.ABIERTO_MODIFICAR.getStatus());
                convBusinessFacade.changeConvocatoriaState(datosGeneralesConvocatoriaDTO);
                RequestContext.getCurrentInstance().reset("form");
                ExternalContext ec = FacesContext.getCurrentInstance().getExternalContext();
                ec.redirect(((HttpServletRequest) ec.getRequest()).getRequestURI());
            } else {
                previousStatus = datosGeneralesConvocatoriaDTO.getStatus();
                if (isGestor()) {
                    datosGeneralesConvocatoriaDTO.setStatus(ConvocatoriaStatusEnum.EN_ESPERA_ESPERA_RESOLUCION.getStatus());
                } else {
                    datosGeneralesConvocatoriaDTO.setStatus(ConvocatoriaStatusEnum.PENDIENTE_VERIFICACION.getStatus());
                }
                convBusinessFacade.changeConvocatoriaState(datosGeneralesConvocatoriaDTO);
                redirectToConvocatoriaList();
            }
            saveNotificacion(previousStatus);
            clearDatosGeneralesConvocatoriaDTOInSession();
        }
    }

    public void saveNotificacion(Long previousStatus) {
        notificacionConvocatoriaAction.save(datosGeneralesConvocatoriaDTO, previousStatus);
    }

    public boolean isConvocatoriaEditable() {

        boolean isEditable = true;

        if (datosGeneralesConvocatoriaDTO != null
                && datosGeneralesConvocatoriaDTO.getStatus() != null
                && (datosGeneralesConvocatoriaDTO.getStatus() == ConvocatoriaStatusEnum.PENDIENTE_VERIFICACION.getStatus()
                        || datosGeneralesConvocatoriaDTO.getStatus() == ConvocatoriaStatusEnum.EN_ESPERA_ESPERA_RESOLUCION.getStatus()
                        || datosGeneralesConvocatoriaDTO.getStatus() == ConvocatoriaStatusEnum.DEFINITIVO.getStatus() || datosGeneralesConvocatoriaDTO.getStatus() == ConvocatoriaStatusEnum.POR_SUBSANAR
                        .getStatus())) {
            isEditable = false;
        }
        return isEditable;
    }

    public static void addShowSuccessfulMessage() {
        FacesMessage msg = new FacesMessage(INFORMATIVE_MESSAGE, SUCCESS_SAVE_MESSAGE);
        FacesContext facesContext = FacesContext.getCurrentInstance();
        msg.setSeverity(FacesMessage.SEVERITY_INFO);
        facesContext.addMessage(null, msg);

    }

    protected void addShowFailedMessage(Throwable t) {
        FacesMessage msg = new FacesMessage(INFORMATIVE_MESSAGE, FAIL_SAVE_MESSAGE);
        FacesContext facesContext = FacesContext.getCurrentInstance();
        msg.setSeverity(FacesMessage.SEVERITY_ERROR);
        facesContext.addMessage(null, msg);
        abstractLogger.error("Ocurrio un error: ", t);
    }

    protected void addShowFailedMessage(Throwable t, String mesage) {
        FacesMessage msg = new FacesMessage(INFORMATIVE_MESSAGE, mesage);
        FacesContext facesContext = FacesContext.getCurrentInstance();
        msg.setSeverity(FacesMessage.SEVERITY_ERROR);
        facesContext.addMessage(null, msg);
        abstractLogger.error("Ocurrio un error: ", t);
    }

    protected void showFacesMessage(Severity severity, String mesage) {
        FacesMessage msg = new FacesMessage(INFORMATIVE_MESSAGE, mesage);
        FacesContext facesContext = FacesContext.getCurrentInstance();
        msg.setSeverity(severity);
        facesContext.addMessage(null, msg);
    }

    protected void redirectToConvocatoriaList() {

        HttpServletRequest origRequest = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
        try {
            FacesContext.getCurrentInstance().getExternalContext().redirect(origRequest.getContextPath() + ConvocatoriaAction.LISTADO_CONVOCATORIA_PAGE);
        } catch (IOException e) {
            abstractLogger.debug("Error en redireccion: ", e);
        }
    }

    public void nextTab() {
        this.save();
        convocatoriaAction.nextTab();
    }

    public boolean isGestor() {

        boolean isGestor = false;
        Collection<? extends GrantedAuthority> rols = SecurityContextHolder.getContext().getAuthentication().getAuthorities();

        for (GrantedAuthority rol : rols) {
            if (rol.getAuthority().equals(GESTOR_CONVOCATORIA_ROL)) {
                isGestor = true;
                break;
            }
        }

        return isGestor;
    }

    public boolean isGestorParcial() {

        boolean isGestorParcial = false;
        Collection<? extends GrantedAuthority> rols = SecurityContextHolder.getContext().getAuthentication().getAuthorities();

        for (GrantedAuthority rol : rols) {
            if (rol.getAuthority().equals(GESTOR_PARCIAL_CONVOCATORIA_ROL)) {
                isGestorParcial = true;
                break;
            }
        }

        return isGestorParcial;
    }

    public boolean mostrarModal(long status) {
        boolean mostrar = false;
        if (isGestor() && (datosGeneralesConvocatoriaDTO.getStatus().equals(status))) {
            mostrar = true;
        }
        return mostrar;
    }

    public boolean mostrarParcial(long status) {
        boolean mostrar = false;
        if (isGestorParcial() && (datosGeneralesConvocatoriaDTO.getStatus().equals(status))) {
            mostrar = true;
        }
        return mostrar;
    }

    protected void saveDatosGeneralesConvocatoriaDTOInSession() {
        FacesContext facesContext = FacesContext.getCurrentInstance();
        HttpSession session = (HttpSession) facesContext.getExternalContext().getSession(true);
        session.setAttribute(DATOS_GENERALES_DTO_SESSION_NAME, datosGeneralesConvocatoriaDTO);
    }

    protected void getDatosGeneralesConvocatoriaDTOInSession() {

sico_webapp/src/main/webapp/pages/convocatorias/edicionConvocatoria/datosGeneralesConvocatoria.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"  
                xmlns:h="http://java.sun.com/jsf/html"  
                xmlns:f="http://java.sun.com/jsf/core"  
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
	<p:accordionPanel id="datosGeneralesAcordeon">
		<p:tab title="Datos">
			<ui:include src="../nuevaConvocatoria/datosGeneralesConvocatoria.xhtml" />
		</p:tab>
		 
		<p:tab title="Finalidad">
			<ui:include src="../nuevaConvocatoria/finalidadConvocatoria.xhtml" />
		</p:tab>
			 
		<p:tab title="Datos de Finalidad">
			<ui:include src="../nuevaConvocatoria/datosFinalidadConvocatoria.xhtml" />
		</p:tab>
			 
		<p:tab title="Jerarquia">
			<ui:include src="../nuevaConvocatoria/jerarquiaConvocatoria.xhtml" />
		</p:tab>
	</p:accordionPanel> 
</ui:composition>

sico_webapp/src/main/webapp/pages/convocatorias/edicionConvocatoria/modalValidacionDatosConvocatorias.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pe="http://primefaces.org/ui/extensions">
	<ui:define name="css_app">
		<link type="text/css" rel="stylesheet" media="all"
			href="#{request.contextPath}/styles/sicoConvocatoria.css?version=#{text['version']}" />
	</ui:define>

	<ui:define name="js_app">
		<script type="text/javascript"
			src="#{request.contextPath}/scripts/sico.js?version=#{text['version']}" />
	</ui:define>


	<h:form id="formValidate">

		<div>
			<p:progressBar value="#{((datosGeneralesConvocatoriaAction.percentage + jerarquiaConvocatoriaAction.percentage
			+ concesionConvocatoriaAction.percentage + datosFinalidadConvocatoriaAction.percentage
			+ configuracionAyudaAction.percentage + observacionesConvocatoriaAction.percentage) * 100) / 600}"
				labelTemplate="{value}%" styleClass="circle-text" id="progress"/>
		</div>

		<div>
			<h:panelGrid columns="1" >
				<p:outputLabel
					value="#{text['validacion.datos.mensaje.porcentaje']}"
					style="padding-left: 100px;" />	
			</h:panelGrid>
		</div>
		<br />
		<div style="padding-top: 30px;">
			<h:panelGrid columns="1" styleClass="topMargin"
				
				rendered="#{(((datosGeneralesConvocatoriaAction.percentage + jerarquiaConvocatoriaAction.percentage
			+ concesionConvocatoriaAction.percentage + datosFinalidadConvocatoriaAction.percentage
			+ configuracionAyudaAction.percentage + observacionesConvocatoriaAction.percentage) * 100) / 600) lt 99}">

				<p:outputLabel
					value="#{text['validacion.datos.mensaje.datos.faltantes']}" 
					/>

			</h:panelGrid>
			<br />
		</div>
		

		<div>
			<p:accordionPanel id="dataValidationAccordion">
			
				<ui:include src="../templates/tabToValidate.xhtml">
					<ui:param name="tabName" value="Finalidad" />
					<ui:param name="tabIndex" value="0" />
					<ui:param name="tabAction" value="#{finalidadConvocatoriaAction}" />
					<ui:param name="isDesactiveLink" value="false" />
				</ui:include>
			 
			 	<ui:include src="../templates/tabToValidate.xhtml">
					<ui:param name="tabName" value="Datos Generales" />
					<ui:param name="tabIndex" value="0" />
					<ui:param name="tabAction" value="#{datosGeneralesConvocatoriaAction}" />
					<ui:param name="isDesactiveLink" value="false" />
				</ui:include>
				
				<ui:include src="../templates/tabToValidate.xhtml">
					<ui:param name="tabName" value="Datos de Finalidad" />
					<ui:param name="tabIndex" value="0" />
					<ui:param name="tabAction" value="#{datosFinalidadConvocatoriaAction}" />
					<ui:param name="isDesactiveLink" value="false" />
				</ui:include>
				
				<ui:include src="../templates/tabToValidate.xhtml">
					<ui:param name="tabName" value="Jerarquía" />
					<ui:param name="tabIndex" value="0" />
					<ui:param name="tabAction" value="#{jerarquiaConvocatoriaAction}" />
					<ui:param name="isDesactiveLink" value="false" />
				</ui:include>
				
				<ui:include src="../templates/tabToValidate.xhtml">
					<ui:param name="tabName" value="Concesión" />
					<ui:param name="tabIndex" value="1" />
					<ui:param name="tabAction" value="#{concesionConvocatoriaAction}" />
					<ui:param name="isDesactiveLink" value="false" />
				</ui:include>
				
				<ui:include src="../templates/tabToValidate.xhtml">
					<ui:param name="tabName" value="Configuración de Ayuda" />
					<ui:param name="tabIndex" value="2" />
					<ui:param name="tabAction" value="#{configuracionAyudaAction}" />
					<ui:param name="isDesactiveLink" value="false" />
				</ui:include>
				
				<ui:include src="../templates/tabToValidate.xhtml">
					<ui:param name="tabName" value="Observaciones" />
					<ui:param name="tabIndex" value="4" />
					<ui:param name="tabAction" value="#{observacionesConvocatoriaAction}" />
					<ui:param name="isDesactiveLink" value="false" />
				</ui:include>
			</p:accordionPanel>
		</div>

		<br />
		<br />
		
		<h:panelGrid columns="1" width="100%" id="action">
			<h:panelGroup style="margin-left: 5%" rendered="#{convocatoriaAction.activeIndex eq 0 and datosGeneralesConvocatoriaAction.datosGeneralesConvocatoriaDTO.status ne 6}">
				<p:commandButton class="botones" actionListener="#{edicionConvocatoriaAction.saveDatosGeneralesTab}"
					value="#{text['boton.guardar']}"
					style="margin-left:24%; margin-right:6px; "
					onclick="PF('modalValidacionDatosWgt').hide();" />

				<p:commandButton class="botones" action="#{datosGeneralesConvocatoriaAction.saveAndSend }"
					value="#{text['boton.enviar.convocatoria']}"
					style="margin-left:10%;"
					onclick="PF('modalValidacionDatosWgt').hide();" />
			</h:panelGroup>
			<h:panelGroup style="margin-left: 5%" rendered="#{convocatoriaAction.activeIndex eq 1 and datosGeneralesConvocatoriaAction.datosGeneralesConvocatoriaDTO.status ne 6}">
				<p:commandButton class="botones" actionListener="#{concesionConvocatoriaAction.save}"
					value="#{text['boton.guardar']}"
					style="margin-left:24%; margin-right:6px; "
					onclick="PF('modalValidacionDatosWgt').hide();" />

				<p:commandButton class="botones" action="#{concesionConvocatoriaAction.saveAndSend}"
					value="#{text['boton.enviar.convocatoria']}"
					style="margin-left:10%;"
					onclick="PF('modalValidacionDatosWgt').hide();" />
			</h:panelGroup>
			<h:panelGroup style="margin-left: 5%" rendered="#{convocatoriaAction.activeIndex eq 2 and datosGeneralesConvocatoriaAction.datosGeneralesConvocatoriaDTO.status ne 6}">
				<p:commandButton class="botones" actionListener="#{configuracionAyudaAction.save}"
					value="#{text['boton.guardar']}"
					style="margin-left:24%; margin-right:6px; "
					onclick="PF('modalValidacionDatosWgt').hide();" />

				<p:commandButton class="botones" action="#{configuracionAyudaAction.saveAndSend}"
					value="#{text['boton.enviar.convocatoria']}"
					style="margin-left:10%;"
					onclick="PF('modalValidacionDatosWgt').hide();" />
			</h:panelGroup>
			<h:panelGroup style="margin-left: 5%" rendered="#{convocatoriaAction.activeIndex eq 4 and datosGeneralesConvocatoriaAction.datosGeneralesConvocatoriaDTO.status ne 6}">
				<p:commandButton class="botones" actionListener="#{observacionesConvocatoriaAction.save}"
					value="#{text['boton.guardar']}"
					style="margin-left:24%; margin-right:6px; "
					onclick="PF('modalValidacionDatosWgt').hide();" />

				<p:commandButton class="botones" action="#{observacionesConvocatoriaAction.saveAndSend}"
					value="#{text['boton.enviar.convocatoria']}"
					style="margin-left:10%;"
					onclick="PF('modalValidacionDatosWgt').hide();" />
			</h:panelGroup>
		</h:panelGrid>

	</h:form>
</ui:composition>